
// This file was generated by Prisma.
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  datasource: {
    url:
      process.env.DATABASE_URL ||
      "postgresql://postgres:password@127.0.0.1:5433/mydb?schema=public",
  },
});
